/**
 * PHP-CRUD-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface IncrementItem {
    id?: number;

    inventory_id?: string;

    title?: string;

    location?: string;

    acquisition_date?: number;

    price?: number;

    supplier?: string;

    comment?: string;

    date?: number;

}
