/**
 * PHP-CRUD-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ReadUser {
    id?: number;

    student_id?: string;

    type?: number;

    email?: string;

    password?: string;

    date?: number;

    name?: string;

    surname?: string;

}
